### ISSUE TITLE
Branches workflow

### ISSUE THREAD

**Issue by xanjohns** [SymbiFlow/symbiflow-common-config#5]
As we finish testing the first feature set of common-config it is important that we decide on a stable, effective workflow for implementing future features.

Our main idea is to create a branch representing each feature set to be implemented:
- community-files
- issue-pr-templates
- auto-formatters
- sphinx-readthedocs

With this approach, different features can be worked in simultaneously and without interference from other development. Each branch (feature set) is tested individually, and only when an acceptable state is reached is the branch merged into `main`. 

The other main advantage to this workflow is that `main` will always contain a stable version of common-config, regardless of what feature we are currently implementing/testing. Repositories could add common-config or update to the latest version of main without having to worry about pulling in partially finished features.

To get started with this, we would need maintainer to create the requested branches.

**Comment by mithro** [comment]
@xanjohns - SymbiFlow uses a "fork and pull" style of development. This is done by forking the repository to your own user, doing the development in your own repository and then sending the pull request. No development should be done directly on the SymbiFlow organization repositories. There is more information at https://reflectoring.io/github-fork-and-pull/


<blockquote><img src="https://reflectoring.io/assets/img/stock/0050-git-1200x628-branded.jpg" width="48" align="right"><div><img src="/assets/img/logo/favicon.ico" height="14"> reflectoring.io</div><div><strong><a href="https://reflectoring.io/github-fork-and-pull/">Github's Fork & Pull Workflow for Git Beginners</a></strong></div><div>If you are new to Git and/or GitHub, it's easy to get overwhelmed by the different workflow models you can use. This post explains the basic fork and pull workflow model that is used on a lot of GitHub repositories.</div></blockquote>
